name: Laravel

on:
  push:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Clear Composer Cache
      run: composer clear-cache
    - name: Install Dependencies
      run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Clear Caches
      run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear
          php artisan queue:restart
          composer dump-autoload
    - name: Run Git Commands
      run: |
          git rm -r --cached .
          git add .

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest

      run: php artisan test
